### ISSUE TITLE
azure devops cherry pick not working

### ISSUE THREAD

**Issue by seonglae** [GitLiveApp/GitLive#100]
![image](https://user-images.githubusercontent.com/27716524/146715197-8377c9ef-87cf-4e1e-a0c3-0ca25b3be06b.png)
- vscode 1.63.2
- gitlive 14.0.8
- azure devops

Cherry pick button not activated and not working

**Comment by Steakeye** [comment]
Hi @seonglae, I'm just reaching out to check that the branch you were trying to cherry-pick belonged to the same repository as the branch you are were working on. Is this correct?

**Comment by seonglae** [comment]
Yes, same repo, different branch, different person

**Comment by Steakeye** [comment]
Would it be possible for you to email a video showing an example of an unsuccessful cherry-pick action to support@git.live?

**Comment by seonglae** [comment]
I emailed it

**Comment by Steakeye** [comment]
Thanks, we're looking into it

**Comment by Ygnys** [comment]
Hi @seonglae, the latest version is now available in the VS Code marketplace and marked as a pre-release (here you can find more on [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)). Will be happy to hear how it works for you!

**Comment by nbransby** [comment]
Closing as fixed in latest version
