### ISSUE TITLE
My GitLive is installing but not working!

### ISSUE THREAD

**Issue by mohammad-fahad** [GitLiveApp/GitLive#101]
I am using macOS version: 12.0.1, after I have installed GitLive the extension is being installed but not working, I couldn't connect it with Github, instead, it's showing me an error at the bottom left corner of my VSCode saying (command 'git.live.showAccountList' not found).

**Comment by Steakeye** [comment]
Hi @mohammad-fahad, please could you give us the VSCode version you're running as well as confirm the version of GitLive that you're using?

**Comment by Ygnys** [comment]
@mohammad-fahad could you also send us a report from VS Code? To do it, navigate to Command Palette  > Report Issue to GitLive. Thanks!

**Comment by Steakeye** [comment]
Hi @mohammad-fahad just wondering if you were able to share a bug report with us?

**Comment by mohammad-fahad** [comment]
Im sorry for the delay guys.

this is the link to my bug report: https://github.com/GitLiveApp/GitLive/issues/106

**Comment by Ygnys** [comment]
I am going to close this issue, please refer to https://github.com/GitLiveApp/GitLive/issues/106 instead
