### ISSUE TITLE
Requesting for call Ringtone feature

### ISSUE THREAD

**Issue by MuttakinHasib** [GitLiveApp/GitLive#102]

**Comment by Ygnys** [comment]
Hi @MuttakinHasib! Thanks for this suggestion, we will work on adding it in the future. If the calling notifications in the IDE are hard to notice, you can enable OS-level notifications via your browser, which are more noticeable. Next time you answer a call, your browser should prompt you to enable push notifications for GitLive. Once enabled you will receive notifications for incoming calls inside your IDE (if open) and also at the OS-level. Clicking on the OS-level notifications will answer the call directly.

**Comment by MuttakinHasib** [comment]
@Ygnys  how can i enable OS Level notification ? I'm using macOS

**Comment by Ygnys** [comment]
@MuttakinHasib  Next time you answer a call, your browser should prompt you to enable push notifications for GitLive.

![2884AA01-E773-4EC9-A586-07A5ACDCAACA_4_5005_c](https://user-images.githubusercontent.com/51296866/148982322-a3729cd6-f7c0-4add-a337-0e06f02897d5.jpeg)


If it doesn't happen:  
- Got to _System Preference_ > _Notifications_ and make sure that notifications are enabled for your browser

![Screenshot 2022-01-11 at 17 24 38](https://user-images.githubusercontent.com/51296866/148982696-78f43580-622a-4943-b1cb-fabeab322fce.png)


- Go to the notifications center on your Mac and make sure that the "do not disturb mode" is off 

![Screenshot 2022-01-11 at 17 21 46](https://user-images.githubusercontent.com/51296866/148982755-66cb7611-6fa2-4f68-918d-1781c53f2a46.png)


- Go to your browser settings and make sure that notifications from meet.git.live are allowed

**Comment by MuttakinHasib** [comment]
not working call coming from vscode. not browser (firefox)

**Comment by MuttakinHasib** [comment]
now it's working. Thank you <3
