### ISSUE TITLE
GitLab Self-Hosted with no Internet

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [GitLiveApp/GitLive#103]
It would be nice if GitLive would also work with git repositories that are on servers that have no connection to the internet.

**Comment by Reedyuk** [comment]
@sschneider-ihre-pvs - totally agree, its on the roadmap.

**Comment by sschneider-ihre-pvs** [comment]
> @sschneider-ihre-pvs - totally agree, its on the roadmap.

Where in the roadmap is it? More the near future or the far?

**Comment by Ygnys** [comment]
@sschneider-ihre-pvs Near future! It will be available in the next few months. There is a separate issue for that which we will update with more details: https://github.com/GitLiveApp/GitLive/issues/96

**Comment by Ygnys** [comment]
@sschneider-ihre-pvs Great news, we now support offline mode which supports certain features without having to use an external repository service! To try it out, please make sure to install the latest version of the plugin available in EAP channel for JetBrains and Pre-Release for VS Code. (Here you can find more on [GitLive's EAP for JetBrains](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains) and [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)). Will be happy to hear how it works for you!

**Comment by sschneider-ihre-pvs** [comment]
Sadly, that doesn't seem to work at all.

**Comment by sschneider-ihre-pvs** [comment]
I think maybe just appearing to be offline is not the same as being ofline
![image](https://user-images.githubusercontent.com/86342787/152298981-6771abac-15d7-4a04-8d0a-bff51dfcdf65.png)

**Comment by nbransby** [comment]
Hi @sschneider-ihre-pvs correct that setting is just to appear offline and has nothing to do with the new functionality.

Can I ask what is not working exactly?

**Comment by sschneider-ihre-pvs** [comment]
Only thing that does work is I see branches of co-workers

**Comment by sschneider-ihre-pvs** [comment]
Thing is, I don't know what should actually work

**Comment by nbransby** [comment]
You should also see any changes from those branches to the file you have open in the gutter of your editor.

Is there a specific feature you were wanting to use?

**Comment by sschneider-ihre-pvs** [comment]
Ok then maybe no one is working on my branch currently. Yes the possible merge conflict view is the main thing. I will test that then

**Comment by sschneider-ihre-pvs** [comment]
At least I got one error now 
![image](https://user-images.githubusercontent.com/86342787/152301309-db4557b4-4a9e-4181-86b4-2888ae58293e.png)

**Comment by sschneider-ihre-pvs** [comment]
and an empty source control expansion panel
![image](https://user-images.githubusercontent.com/86342787/152301422-0e4773cf-d037-4c45-8c52-3a4f6890e0e3.png)

**Comment by sschneider-ihre-pvs** [comment]
![image](https://user-images.githubusercontent.com/86342787/152304170-2af5b2fc-57d3-4fd7-a1fc-a3dd1fc7925f.png)

**Comment by michaelprichardson** [comment]
Hi @sschneider-ihre-pvs, could you please explain the steps to how you got these errors?

> ![image](https://user-images.githubusercontent.com/86342787/152301309-db4557b4-4a9e-4181-86b4-2888ae58293e.png)

> ![image](https://user-images.githubusercontent.com/86342787/152304170-2af5b2fc-57d3-4fd7-a1fc-a3dd1fc7925f.png)

**Comment by sschneider-ihre-pvs** [comment]
I just opened the gitlive panel

**Comment by nbransby** [comment]
I believe these issues have been fixed in the lastest version but please reopen if you find that is not the case
