### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mohammad-fahad** [GitLiveApp/GitLive#106]
Issue Type: <b>Bug</b>

I am using macOS version: 12.0.1, after I have installed GitLive the extension is being installed but not working, I couldn't connect it with Github, instead, it's showing me an error at the bottom left corner of my VSCode saying (command 'git.live.showAccountList' not found).

Extension version: 14.0.8
VS Code version: Code 1.60.1 (Universal) (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 06639fe5-997e-4df4-8054-d89b7a492375|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
py55gd98cf:30419166
vscexrecpromp3t2:30407763

```

</details>

**Comment by Steakeye** [comment]
Hi @mohammad-fahad,

Thanks for providing this information to us. Can I also confirm with you that you have VSCode LiveShare installed? We understand that the latest LiveShare plugin has some issues that affect us because GitLive integrates with LiveShare when it's present.

We have a fix for the LiveShare issue coming in our next release, so we'll let you know when that's ready for you to try 🙂 In the meantime you might want to see if disabling LiveShare fixes the issue.

**Comment by Ygnys** [comment]
Hi @mohammad-fahad, the latest version is now available in the VS Code marketplace and marked as a pre-release (here you can find more on [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)). Will be happy to hear how it works for you!

**Comment by nbransby** [comment]
This has been fixed in the latest version
