### ISSUE TITLE
Polling of firestore failing

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [GitLiveApp/GitLive#107]
Issue Type: <b>Bug</b>

Maybe add a max retry or some feature toggle to disable the polling on firebase urls.

`E Failed to connect to firestore.googleapis.com through proxy`

Extension version: 15.0.1
VS Code version: Code - Insiders 1.65.0-insider (bb221a61d29deabd99ee9431736d04f2175cb596, 2022-02-11T05:19:13.554Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.40GB free)|
|Process Argv|--log-net-log=netlog.json --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc008:30436272
pythonvsnew555:30426298
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849
vscgsvid2:30433758

```

</details>

**Comment by nbransby** [comment]
Hi @sschneider-ihre-pvs where you seeing this error?

**Comment by sschneider-ihre-pvs** [comment]
vscode devtools
