### ISSUE TITLE
AWS codecommit support

### ISSUE THREAD

**Issue by AustinAmoruso** [GitLiveApp/GitLive#108]
Can you support aws codecommit also why doesn't this just work with any git regardless of the hosting?

**Comment by nbransby** [comment]
Hi @AustinAmoruso you'll be pleased to know our latest version released yesterday does exactly that - support any git repository, you can read about it here: https://blog.git.live/gitlive-15.0-offline-merge-conflict-detection-across-all-branches-for-any-git-repository#offline-mode

**Comment by AustinAmoruso** [comment]
I'm looking for the live features, such as collaborate and instant conflicts. Is there an sdk or api so I could setup a solution for aws?

**Comment by Ygnys** [comment]
Hi @AustinAmoruso unfortunately there isn't. AWS CodeCommit support with live features is on our roadmap, but we don't have a date we should share just yet. Will update this issue as soon as we are ready to share more details.
