### ISSUE TITLE
intellij - support gitlab enterprise instances

### ISSUE THREAD

**Issue by DetachHead** [GitLiveApp/GitLive#110]
the gitlab option here opens gitlab.com, there doesn't seem to be an option to specify a different gitlab instance

![image](https://user-images.githubusercontent.com/57028336/158086748-7ebde5d4-a8c2-4e3e-bce2-4382184759a9.png)

**Comment by Ygnys** [comment]
Thanks for this suggestion, we will make sure to add it in the future!

**Comment by DetachHead** [comment]
i don't seem to have that option, see https://github.com/GitLiveApp/GitLive/issues/111#issuecomment-1068579622

**Comment by ainesophaur** [comment]
I seem to have the same issue with my instance of PhpStorm. I have a self hosted gitlab server and the link to "Configure new GitLab Server" never appears. Ive tried a combination of switching between SSH and HTTPS remote urls for git (just in case it mattered.) I also attempted with a fresh clone of the repo from PhpStorm's "checkout from VCS option"

Mac OS X 12.3
PhpStorm 2021.3.2
GitLive 15.0.5
<img width="1665" alt="Screen Shot 2022-03-18 at 11 40 52 AM" src="https://user-images.githubusercontent.com/4686198/159035712-0bf58ab2-0b9d-4934-8950-a86149ddd3ae.png">



The project name is kebab cased and the gitlab server ends in a .io TLD (just in case it matters)

**Comment by Ygnys** [comment]
Hi @ainesophaur @DetachHead could you check if your remote URL is accessible from the internet via HTTP or HTTPS (via the browser)? If the remote URL is accessible only internally, you can only use GitLive in offline mode (the sign-in popup won't appear) or open up port 80 or 443 to allow us to connect.

**Comment by ainesophaur** [comment]
That would explain it as the self hosted gitlab isnt publicly accessible. Does gitlive only need to hit the API endpoints of gitlab?

**Comment by Ygnys** [comment]
@ainesophaur We check the root/home page for accessibility, if you allow traffic on either port 80 or 443 to your server we should be able to connect

**Comment by DetachHead** [comment]
is it possible for that check to be done locally by the extension itself?

**Comment by nbransby** [comment]
> is it possible for that check to be done locally by the extension itself?

We are working on support for this but its not currently possible

**Comment by DetachHead** [comment]
awesome, is there an issue tracking this that i can follow?

**Comment by Ygnys** [comment]
@DetachHead I created a new issue for this: https://github.com/GitLiveApp/GitLive/issues/113
