### ISSUE TITLE
intellij - users/branches not visible when not signed in

### ISSUE THREAD

**Issue by DetachHead** [GitLiveApp/GitLive#111]
from @KotlinIsland's comment below
> @Ygnys I don't think anything is being signed in, I think it uses git repo information without signing in, it's just that it seems completely broken in Idea: 
> ![image](https://user-images.githubusercontent.com/65446343/158284953-00babe51-7cd7-4a52-b013-0da7f0248996.png)
> 
> Compared to VSCode:
> ![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/65446343/158285058-d1db67e1-1760-4144-ac3f-f32f2f5169c4.png)
> (Edited with GnuIMP (Green Is My Pepper))
> 
> Idea is not showing any information at all, while vscode is showing all information, I think the title of this issue is incorrect.

**Comment by Ygnys** [comment]
Hi @DetachHead , thanks for reporting this! When you first open your IDE, go to _View > Apparence_ and make sure that _Tool Window Bars_ are enabled. You should be able to see the GitLive icon at the bottom

![Screenshot 2022-03-14 at 17 01 33](https://user-images.githubusercontent.com/51296866/158212435-92ff81db-0ce7-416c-9868-e3c41292457d.png)

After clicking on the icon, the GitLive team window should appear, and from there you can sign in to the hosting service you're using.

![Screenshot 2022-03-14 at 17 02 44](https://user-images.githubusercontent.com/51296866/158212475-f20c6371-8852-4a1e-b7f8-37f12befea7e.png)

**Comment by DetachHead** [comment]
Thanks, but I mean it would be more convenient if it automatically signed me in like the vscode extension seems to do (admittedly I have no idea how it does that)

**Comment by KotlinIsland** [comment]
@Ygnys 
I don't think anything is being signed in, I think it uses git repo information without signing in, it's just that it seems completely broken in Idea:
![image](https://user-images.githubusercontent.com/65446343/158284953-00babe51-7cd7-4a52-b013-0da7f0248996.png)

Compared to VSCode:
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/65446343/158285058-d1db67e1-1760-4144-ac3f-f32f2f5169c4.png)
(Edited with GnuIMP (Green Is My Pepper))


Idea is not showing any information at all, while vscode is showing all information, I think the title of this issue is incorrect.

**Comment by DetachHead** [comment]
updated the issue

**Comment by Ygnys** [comment]
Hi @KotlinIsland could you send the screenshot of the whole IJ IDE? Did you manage to locate the sign in button? 

The message you are seeing suggests that there are no branches ahead of your default branch in the project you have opened - if that's the case you won't see anything in the offline mode. If there are some branches ahead of your default branch that are older than 3 months you can use "stale" filter to display them. You can find it by clicking on the eye icon (other filters will be available after signing in). 

You can see here that there are no  branches (newer than 3 months) ahead of my default branch in blog-1 repo,

![Screenshot 2022-03-15 at 19 09 16](https://user-images.githubusercontent.com/51296866/158443892-0b30c9ec-9655-4413-9711-dc1006527438.png)

But there are some branches older then 3 months that are visible after using "stale" filter

![Screenshot 2022-03-15 at 20 24 43](https://user-images.githubusercontent.com/51296866/158455797-99494e55-9ecd-4482-86b8-0491ea4dcbd2.png)


Let me know if that helps

**Comment by KotlinIsland** [comment]
@Ygnys Doesn't seem to help at all, the plugin seems completely non-functional, as per my previous screenshots, the vscode plugin seems to be working fine.
![image](https://user-images.githubusercontent.com/65446343/158491021-94502a95-a6f3-433c-8ae9-c3e5860b25c5.png)

**Comment by Ygnys** [comment]
@KotlinIsland, Could you please confirm your GitLive version and IJ version and send us a GitLive report from your IDE? In order to do that, go to _Find Action_ ( ⌘ ⇧ A) > _Report Issue to GitLive_. Click on the _IDE error occurred_ notification, add a message with details and submit. Thanks!


![error-report-3](https://user-images.githubusercontent.com/51296866/158578107-e2f1440d-2e22-4eb0-bd62-99ef4d0dd204.gif)

**Comment by DetachHead** [comment]
plugin version: 15.0.5
idea version: 2021.3

sent an error report

**Comment by nbransby** [comment]
@DetachHead could you let us know the remote URLs for this clone you have open in the IDE? You can send them to support@git.live

**Comment by DetachHead** [comment]
unfortunately can't as the gitlab instance i'm using is not publicly accessible

**Comment by Ygnys** [comment]
@DetachHead To sign in to GitLive the repository needs to be accessible via Internet. The offline mode should work properly, I assume you opened different repositories in VS Code and IntelliJ?

**Comment by DetachHead** [comment]
same repo in both screenshots.

how come the repository needs to be internet accessible? is there any chance of this requirement being removed in the future?

**Comment by KotlinIsland** [comment]
@Ygnys 
> To sign in to GitLive the repository needs to be accessible via Internet. The offline mode should work properly, I assume you opened different repositories in VS Code and IntelliJ?

This was the same repository :(

I have tested the plugin with a different(public) repository (albeit on a different machine) and it worked flawlessly.

**Comment by KotlinIsland** [comment]
Is this related? https://dev.to/gitlive/gitlive-now-works-with-any-git-repository-in-vs-code-304o

Does gitlive not support 'offline mode' in Idea?

**Comment by nbransby** [comment]
@DetachHead could you send another report but after restarting the ide and only having a single ide window open which is the project that is not working as expected in GitLive, thanks

**Comment by nbransby** [comment]
> Is this related? https://dev.to/gitlive/gitlive-now-works-with-any-git-repository-in-vs-code-304o
> 
> Does gitlive not support 'offline mode' in Idea?

it does work in idea also

**Comment by Ygnys** [comment]
Closing the issue because it needs more information and has not had recent activity. Please re-open the issue if more details can be provided. Thanks!

**Comment by KotlinIsland** [comment]
@Ygnys Is there any specific information that would help? I really want to use GitLive but this issue is completely blocking all usage.

**Comment by Ygnys** [comment]
Hi @KotlinIsland, could you update GitLive to the newest version and see if it's still happening? If so, could you send us the report,  but after restarting the IDE and only having a single IDE window open which is the project that is not working as expected in GitLive?
Thanks!

**Comment by KotlinIsland** [comment]
Unfortunately I can't, as I'm using Idea 2022.2 and GitLive only crashes on this version, but I can get someone else to do this. Thanks

**Comment by Ygnys** [comment]
@KotlinIsland what version of GitLive are you using? Could you update to the newest one? GitLive should now work correctly with 2022.X IDEs

**Comment by KotlinIsland** [comment]
@Ygnys I am using 2022.2 IDE with GitLive 15.0.11
![image](https://user-images.githubusercontent.com/65446343/182307746-37166e80-cd56-4f87-9c59-709e9109fa91.png)

**Comment by Ygnys** [comment]
Hi @KotlinIsland, thanks for the update! We are aware of the plugin not working correctly with IJ 2022.2 and looking into this issue. Will update you once we release a fix.

**Comment by Ygnys** [comment]
Hi @KotlinIsland! We have recently released EAP version of GitLive 16 and we believe it should fix the issues you've previously reported. You can find it [here](https://plugins.jetbrains.com/plugin/11955-gitlive/versions/eap). Will be happy to hear how it works for you!

**Comment by KotlinIsland** [comment]
I believe this issue is resolved 🚀🚀🚀🚀🚀🚀🚀🚀🚀
