### ISSUE TITLE
GitLab self-hosted support for servers not accessible via the internet

### ISSUE THREAD

**Issue by Ygnys** [GitLiveApp/GitLive#113]
We are working on this feature and will update the issue once it's ready

**Comment by mitea1** [comment]
any progress or possible release date?

**Comment by Ygnys** [comment]
Hi @mitea1, we are working on this feature, but I don't have a date to share just yet. I will let you know as soon as I have more updates on this!

**Comment by nbransby** [comment]
This is available since GitLive 17.0.0 - https://blog.git.live/GitLive-17.0-Simplified-onboarding-and-enhanced-security#improved-support-for-gitlab-self-hosted
