### ISSUE TITLE
"No git repositories found in this project" when opening a sub-folder in IDE

### ISSUE THREAD

**Issue by decates** [GitLiveApp/GitLive#116]
If I open a sub-folder of a git repository in IDE (either Jetbrains Webstorm or VSCode), GitLive displays the message "No git repositories found in this project" and the plugin doesn't load up.

For example, if ~/myrepo has a `.git` folder in it and I open `~/myrepo/ui-project` in the IDE, the GitLive plugin doesn't work. 

I gather from other issues that this may be 'by design' - it looks for a `.git` folder at the root of the IDE workspace. However, I don't believe this is correct: any other souce-control IDE plugin would expect to work from a sub-folder: it should search up the folder structure for any parent that has a `.git` folder in it, rather than expect to always be at the root.

**Comment by nbransby** [comment]
Hi @decates yes we want to add support for this. Could you tell me a little more about your use case? It is a monorepo and you only work in that subfolder? Would you also like the information displayed in GitLive to be restricted to sub folder? For example only showing you the teammates and changes from that folder?

**Comment by Ygnys** [comment]
Hi @decates,  support for this has been added to our EAP version. You can find it [here](https://plugins.jetbrains.com/plugin/11955-gitlive/versions/eapl) (JetBrains IDEs) or go to _Extensions_ > _GitLive_ and choose _Switch to Pre-Release Version_ in VS Code. Will be happy to hear how it works for you!

**Comment by Ygnys** [comment]
Closing the issue, the support for this is now included in the stable version.
