### ISSUE TITLE
Not able to sign in in bitbucket on PHPStorm

### ISSUE THREAD

**Issue by bertog** [GitLiveApp/GitLive#120]
Hi there,

I'm trying to link GitLive on PHPStorm to our bitbucket stuff. The tool Window show this:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/7644360/167386337-e3b8cde8-b2ad-4134-956d-0c1bd547be87.png">

After click the sign in link it open a Bitbucket Window say that's everything is ok and I can close the tab, but nothing happen in GitLive.

Going in the settings this appear:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/7644360/167386646-57037a43-bdf2-4443-a06e-89d70adfdd04.png">

But click on the link "Sign into an account" or on the plus sign top left nothing happen

Any suggestion?

Guido Bertolino

**Comment by Ygnys** [comment]
Hi @bertog, thanks for reporting, we are aware of the problem and trying to fix it asap. Sorry for the inconvenience, will update you as soon as the issue is resolved.

**Comment by bertog** [comment]
Yes it working now :) Thanks :)

Guido

**Comment by Eason51** [comment]
Same problem with versions from 11 to the newest on android studio

**Comment by Ygnys** [comment]
Hey @Eason51 could you provide us with the steps to reproduce the issue (also screenshots would be helpful if that's possible)? Just to confirm, are you trying to sign in with Bitbucket?
Could you also let us know what OS, GitLive version, and exact IDE version you're using? Thanks!

**Comment by Eason51** [comment]
> 

Android Studio version 2021.2.1
GitLive version 15.0.8
It has been installed in a Github repository
![1](https://user-images.githubusercontent.com/66631204/169027315-7f435e21-c7c5-443b-a132-ff62f818ef12.jpg)
Image 1 is the interface after I installed GitLive in Android Studio, I cannot click anything in the left panel, except the "settings" option.
![2](https://user-images.githubusercontent.com/66631204/169027571-3afef78a-b967-42ff-bb5f-bd3265ce41d9.jpg)
Image 2 is the "settings" interface, when I click the plus sign on the top left, or click "sign into an account", nothing has happened

**Comment by Ygnys** [comment]
Thanks, @Eason51, we will look into it!

**Comment by michaelprichardson** [comment]
Hi @Eason51,

Thanks for those steps! Can you confirm you are connected to the internet? Are you using a proxy or VPN?

In offline mode you will only see users that have branches which are ahead of master.

You should see the sign in link from the GitLive window:
![image](https://user-images.githubusercontent.com/5164099/169061639-7736397e-d51d-4522-b9b4-4e7360c07d46.png)

This is what it should look like when trying to add an account from the settings:
![image](https://user-images.githubusercontent.com/5164099/169061854-15933f83-d278-40b2-b7a3-2612cb1dae21.png)

**Comment by michaelprichardson** [comment]
Thanks for the fast reply @Eason51!

I just tested with and without a VPN enabled and it worked. Could you tell me which country you are trying to use Gitlive from?

**Comment by Eason51** [comment]
> Thanks for the fast reply @Eason51!
> 
> I just tested with and without a VPN enabled and it worked. Could you tell me which country you are trying to use Gitlive from?

@michaelprichardson I am accessing from China, and I have tested my VPN from different Asia countries, but none of them work.

**Comment by michaelprichardson** [comment]
@Eason51 Could you try your VPN from a European country?

**Comment by Eason51** [comment]
> @Eason51 Could you try your VPN from a European country?

@michaelprichardson I tried a UK one, but the problem persists. It's okay, using gitlive is not a must for my project, so it doesn't really matter if the problem persists. I just hope it's a special case that never happens to other users.
