### ISSUE TITLE
Error in VSCode extension (Insider version)

### ISSUE THREAD

**Issue by LucasGasparinoBSC** [GitLiveApp/GitLive#124]
Greetings!

When opening any project that is a git repo, I get the following error message from VSCode:

Cannot read properties of undefined (reading 'repository') (TypeError)

Apart from the message, the extension doesn't seem to be working at all. This has happened recently (last week I had no issues with it). Any idea what might be happening? I tried Googling around, but no one else seems to have posted about this yet.

In any case, thanks for the attention!

**Comment by Ygnys** [comment]
Hey @LucasGasparinoBSC, thanks for reporting, we are looking into this issue.

**Comment by Ygnys** [comment]
Hey @LucasGasparinoBSC, the issue has been fixed in the newest version.

**Comment by LucasGasparinoBSC** [comment]
Thanks a lot, already have the new one working! Super useful extension btw, I love it!

**Comment by Ygnys** [comment]
Thank you @LucasGasparinoBSC, happy to hear you are enjoying GitLive! I am closing this issue, but feel free to reach out to us with any additional feedback or questions you might have :)
