### ISSUE TITLE
GitLive causes Intellij to show branches from the wrong project

### ISSUE THREAD

**Issue by hailwood** [GitLiveApp/GitLive#126]
Please see https://youtrack.jetbrains.com/issue/IDEA-299233

**Comment by nbransby** [comment]
Thanks for reporting, does it occur only with the new UI?

Also the screencast is not visible on the youtrack issue, could you share that?

**Comment by hailwood** [comment]
Hi @nbransby,

Just checked and it does appear to only happen with the new UI

[git branch issue.webm](https://user-images.githubusercontent.com/709773/182719081-7c9b86c4-bdc1-4cc5-b0a4-1faa4db9365f.webm)

**Comment by nbransby** [comment]
I suspect it might be an issue in the beta of the new UI and it's compatibility with existing plugins in that case. 

Worth submitting the issue with the New UI beta (not sure where that lives)

**Comment by hailwood** [comment]
Thanks @nbransby,
I've gone back to the original issue and let them know it's a new UI issue, we'll see what they say.
In the meantime if you'd like to look into it, let me know and I'll email you how to enable the new UI.

Cheers

**Comment by nbransby** [comment]
@hailwood I am closing this as I believe it has been fixed but please re-open if you can still reproduce
