### ISSUE TITLE
The placeholder texts on the blog

### ISSUE THREAD

**Issue by Ygnys** [GitLiveApp/GitLive#13]
While clicking through our website, somehow I ended up here: https://docs.git.live/blog/
Unfortunately, I don't remember the steps I took, I think clicked "terms" at the bottom of the landing page.
<img width="1065" alt="Screenshot 2020-11-12 at 14 49 32" src="https://user-images.githubusercontent.com/51296866/98948136-59ad0c80-24f6-11eb-8296-0a76b163ff84.png">

**Comment by FredCoen** [comment]
@SuDa2103 can you take that route out?
