### ISSUE TITLE
Option to disable code hover popup content on vscode

### ISSUE THREAD

**Issue by grantwest** [GitLiveApp/GitLive#132]
The content that GitLive adds to the code hover popup on vscode hides useful information. Because the GitLive content is first and so long, it hides the errors and docs:
![top](https://user-images.githubusercontent.com/4594800/194617997-c0269936-e360-414a-9de1-609a247f83a6.png)

To see the actual language server error you need to scroll all the way to the bottom:
![bottom](https://user-images.githubusercontent.com/4594800/194618149-d9f70f32-d237-4d8d-bc86-1cabec62d7ef.png)

I'd like to be able to disable having the GitLive content in the code hover popups.

**Comment by Ygnys** [comment]
Hi @grantwest, what vs code version are you using? The problem you described was a VS Code issue and as far as we can tell it has been fixed in the latest version.

**Comment by nbransby** [comment]
You can hide these when you need to now in version 18.0.5 by right-clicking in the gutter and selecting None
<img width="543" alt="image" src="https://github.com/user-attachments/assets/1a5897cb-1361-4c32-aa15-dd6ea601e096">
