### ISSUE TITLE
(🐞) IDEA: gutter icon shown at end of file when there are no changes

### ISSUE THREAD

**Issue by KotlinIsland** [GitLiveApp/GitLive#135]
It seems to me that when I am looking at a file that has any GitLive markers in the gutter, there is always an incorrect entry at the bottom of the file

![image](https://user-images.githubusercontent.com/65446343/199171548-9dc83fb3-9491-4a0b-980f-2e2e80a28386.png)

This commit does not edit the end of the file

PyCharm 2022.3 EAP, GitLive 16.0.0

**Comment by Ygnys** [comment]
Thanks for reporting @KotlinIsland, we are working on fixing this issue

**Comment by nbransby** [comment]
18.0.0 has now been released to stable which fixes this issue, thanks for reporting.
