### ISSUE TITLE
(🐞) Open in GitLab doesn't go to the right url when it's nested in groups

### ISSUE THREAD

**Issue by KotlinIsland** [GitLiveApp/GitLive#136]
Here I have a project that is nested two group deep, ie `https://domain/outer-group/inner-group/project`. When I click the "open branch on GitLab" link on a gutter icon diff, it takes me to a 4️⃣0️⃣4️⃣ page 😢.

![image](https://user-images.githubusercontent.com/65446343/199174679-67f1e763-9edc-4814-91ea-cc7efbec864e.png)

![image](https://user-images.githubusercontent.com/65446343/199174668-1aad6b4b-1073-4aa6-a7f8-fabbb7d6fdcf.png)

As you can see (kinda) GitLive has only included the outer group in the url.

**Comment by Ygnys** [comment]
Thanks for reporting @KotlinIsland, we will try to include a fix for this 🐞 in the next release

**Comment by Ygnys** [comment]
Hi @KotlinIsland, this has been fixed in the latest stable version, let us know how it works for you :)

**Comment by KotlinIsland** [comment]
Awesome, it's working now, thanks 🚀
