### ISSUE TITLE
(👁/🐞) Icon for tool window is barely visible with the new UI preview

### ISSUE THREAD

**Issue by KotlinIsland** [GitLiveApp/GitLive#137]
# GitLive (barely visible):
![image](https://user-images.githubusercontent.com/65446343/200474266-92bd8c72-fe73-42ec-ba00-769cae657de4.png) ![image](https://user-images.githubusercontent.com/65446343/200477056-06cffcaa-7ef6-49f3-8f3e-bd15346d84e2.png)

# Services (very visible): 
![image](https://user-images.githubusercontent.com/65446343/200474285-25e72ca6-d38b-4ca0-8cb8-45eb9b0f9fa0.png) ![image](https://user-images.githubusercontent.com/65446343/200477086-274adf6b-459b-4361-9f54-5c92d9c7cdeb.png)

**Comment by Ygnys** [comment]
Thanks for reporting @KotlinIsland, we will look into this!

**Comment by Ygnys** [comment]
Hi @KotlinIsland, this has been fixed in the newest update
