### ISSUE TITLE
vscode error - "FirebaseFirestoreException: UNAVAILABLE: Failed to get document because the client is offline."

### ISSUE THREAD

**Issue by DetachHead** [GitLiveApp/GitLive#138]
my repository is hosted on an internal gitlab instance btw

![image](https://user-images.githubusercontent.com/57028336/200484188-7ccfd253-48c4-4961-b2f0-a66008e16352.png)

**Comment by Ygnys** [comment]
Hi @DetachHead, thanks for reporting, we are working on a fix for this issue.

**Comment by Ygnys** [comment]
Hi @DetachHead, we believe it to be a transient issue, has it happened since?

**Comment by DetachHead** [comment]
@Ygnys still happening, version 16.1.3

**Comment by Ygnys** [comment]
@DetachHead thanks, is restarting the IDE fixing the issue?

**Comment by DetachHead** [comment]
it seems to work for a few seconds then crashes with that error in the OP

**Comment by Ygnys** [comment]
Hi @DetachHead, are there any particular steps to reproduce this issue in your case? Does this happen every time you use the plugin? Thanks

**Comment by DetachHead** [comment]
every time. this time i recorded a gif:

1. open vscode
2. select gitlive tab
3. wait about 1 minute

![](https://user-images.githubusercontent.com/57028336/215394116-7382c7a2-04e3-480a-b1fa-e2af6470dc45.gif)

**Comment by Ygnys** [comment]
Thanks @DetachHead, we are working on it. Appreciate your patience, I will update you as soon as we release a fix for this.

**Comment by nbransby** [comment]
@DetachHead this should be fixed in the latest pre-release, please re-open if thats not the case
