### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by CodePeacock** [GitLiveApp/GitLive#141]
Type: <b>Bug</b>

Install GitLive extension for VSCode. Start Extension Bisect. 

Extension version: 16.0.3
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100T CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by CodePeacock** [comment]
This is a new issue. I found this extension features exciting so I tried. It wont' work

![image](https://user-images.githubusercontent.com/71129528/206649768-0a6a916f-cf92-4c43-ac9b-a320f8ecbe3a.png)

I've tried restarting, reinstalling. But it won't work.

Please respond ASAP 🙏

**Comment by Ygnys** [comment]
Hi @FireStorm69 thanks for reporting! We have now released a fix for this issue, please make sure to update GitLive to version 16.0.4. Let us know how it works for you :)

**Comment by CodePeacock** [comment]
> Hi @FireStorm69 thanks for reporting! We have now released a fix for this issue, please make sure to update GitLive to version 16.0.4. Let us know how it works for you :) 

Oh. That's awesome. Thank you 😊 all. I'll install ASAP and inform you.

**Comment by CodePeacock** [comment]
The extension works. But it doesn't make any sense. It can't switch from my master branch to my main branch 🥺

**Comment by nbransby** [comment]
Could you share some screenshots? What do you mean it can't switch between the branches?

**Comment by CodePeacock** [comment]
![image](https://user-images.githubusercontent.com/71129528/206853421-6b797166-6f71-490d-8fb5-e61be88ada2d.png)
Above is my master branch. I don't work on that branch. I select team "virtual-voice-assistant"

**Comment by Ygnys** [comment]
Hi @FireStorm69 , I the tree you should see the branches ahead of your current branch. GitLive performs a [three dot diff](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons) between your local HEAD and the heads of all the remote branches in your repository to populate the tree in the repository view (in your case `virtual-voice-assistant`).  You can use the  view options to customize this diffing process and what you see in the tree 

![Screenshot 2022-12-12 at 18 35 11](https://user-images.githubusercontent.com/51296866/207114752-0b4bef94-93f7-4976-8653-83582bad889f.png)

**Comment by CodePeacock** [comment]
> Hi @FireStorm69 , I the tree you should see the branches ahead of your current branch. GitLive performs a [three dot diff](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons) between your local HEAD and the heads of all the remote branches in your repository to populate the tree in the repository view (in your case `virtual-voice-assistant`).  You can use the  view options to customize this diffing process and what you see in the tree 
> 
> ![Screenshot 2022-12-12 at 18 35 11](https://user-images.githubusercontent.com/51296866/207114752-0b4bef94-93f7-4976-8653-83582bad889f.png)
> 

I've tried this. It still won't work. The branch me and my team mates are working on is the same 🥺.

**Comment by Ygnys** [comment]
Hi, do you mean you can't see the changes your teammates made to the main branch? Could you send a screenshot with the full GitLive sidebar visible? If you prefer, you can send it to support@git.live.

**Comment by CodePeacock** [comment]
![image](https://user-images.githubusercontent.com/71129528/207408960-44b65299-f783-4957-863e-e57b41cf41fd.png)

We changed some settings and it works now 😁. It is slightly slow in showing where my team mate is working and in which file.

I would like to know how this extension works.

**Comment by Ygnys** [comment]
@FireStorm69 happy to hear the extension works correctly for you now! Since the initial problem has been solved I am going to close this issue. If you want to learn more about GitLive I recommend checking out our docs: https://docs.git.live/ and the security page: https://app.git.live/security
