### ISSUE TITLE
Intellij IDEA, code coverage not showing when using GitLive plugin

### ISSUE THREAD

**Issue by agent3bood** [GitLiveApp/GitLive#143]
Hello 

When running tests with coverage the IDE shows colored columns at the left for coverage information, but when the GitLive plugin is active this area is taken and coverage information is lost.

<img width="115" alt="Screen Shot 2023-02-01 at 19 47 32" src="https://user-images.githubusercontent.com/771902/216107690-367cfdf8-e87a-4dc9-b751-c0b14e23bfb9.png">

**Comment by agent3bood** [comment]
Update: when I hide the GitLive indicator, the code coverage show up correctly.

<img width="115" alt="Screen Shot 2023-02-01 at 20 40 27" src="https://user-images.githubusercontent.com/771902/216120612-0aa258ce-e820-4afc-8a4f-6e20d2155914.png">

**Comment by nbransby** [comment]
Hi @agent3bood this has been fixed in the latest version of the plugin but you need to enable the New UI in IntelliJ to see coverage and the GitLive indicators at the same time
