### ISSUE TITLE
Gitea integration

### ISSUE THREAD

**Issue by ndgayan** [GitLiveApp/GitLive#145]
Our organization uses Gitea. Could you add an option to integrate into Gitea?

https://gitea.io/en-us/

**Comment by ndgayan** [comment]
Just noticed there is an open issue for this.

**Comment by Ygnys** [comment]
Hi @ndgayan, you can also vote for which repository hosting service we should add support next [here](https://github.com/GitLiveApp/GitLive/discussions/130) - the more upvotes Gitea gets, the more we will prioritize it!
