### ISSUE TITLE
Stop GitLive Diff comment when hovering code words in vscode

### ISSUE THREAD

**Issue by michaelsogos** [GitLiveApp/GitLive#150]
Hi There,

As you know, in vs code, when I stay over any word, a suggestion window appear tell me about my code (types, issues, docs, etc.).
I really don't need to know the commit differences for that particular line of code so often, so it is annoying me and wasting my productivity because the information that I really need to see is some before and some after the diff comments, and then I have to scroll.

Could you just let it be configurable in vs code settings? And by default to be "off"?

On more suggestion, you should know that if I just over the mouse a suggestion panel appears, but if I press SHIFT while over the word, again a suggestion panel appears but with different information than before.
Maybe you could do something like SHIFT+ALT (or SHIFT+OPT on Mac) to show a suggestion window with just the diff comments inside 😄 .

**Comment by nbransby** [comment]
We did actually bring this up with the vscode team as they don't provide the ability to demote the diffs to the bottom of the popup:
https://github.com/microsoft/vscode/issues/159759#issuecomment-1234301868

They weren't interested in addressing the issue but I thought they had fixed it as we could not reproduce it recently - how often does it happen for you? Are you able to provide a screenshot?

**Comment by nbransby** [comment]
Once vscode releases this feature we can finally solve this issue... https://code.visualstudio.com/updates/v1_89#_hover-verbosity-level

**Comment by nbransby** [comment]
You can now use `Hide diff in hover popup` to do this
<img width="530" alt="image" src="https://github.com/user-attachments/assets/7bd5d8b2-de8f-4e73-bd74-0e2fd00ddae6">
