### ISSUE TITLE
Unable to sign in gitlive

### ISSUE THREAD

**Issue by zeric2tan** [GitLiveApp/GitLive#152]
![Snipaste_2023-11-20_12-19-31](https://github.com/GitLiveApp/GitLive/assets/25836581/b386ec97-3364-450f-9af2-e6444d37390e)
![Snipaste_2023-11-20_12-19-40](https://github.com/GitLiveApp/GitLive/assets/25836581/f7cddd7f-f2d9-4143-bf16-09226590bdb0)
i facing a issued that gitlive no way to sign in gitlive and unable to click sign in with error as attachment

**Comment by nbransby** [comment]
Hi, could you try with the prerelease version? Here is how to install it: https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode#how-to-join-the-eap-in-vs-code

**Comment by zeric2tan** [comment]
Hi, i had install rerelease version, but still have same error, i had use ">report" to send a report
![Snipaste_2023-11-20_13-13-48](https://github.com/GitLiveApp/GitLive/assets/25836581/3495e5cf-0db0-4853-b1c1-721e92b21267)
![Snipaste_2023-11-20_13-12-43](https://github.com/GitLiveApp/GitLive/assets/25836581/6fee387b-d7a5-487b-b941-c7326c524270)
![Snipaste_2023-11-20_13-12-53](https://github.com/GitLiveApp/GitLive/assets/25836581/ddab5b20-394a-4bcd-96d8-35b79cc2b475)

**Comment by nbransby** [comment]
Could you confirm  the version of vscode and the contents of the Output - Extension Host window?
![image](https://github.com/GitLiveApp/GitLive/assets/1386607/039dd0f9-5a5a-46e2-a8da-f45d851eb46d)
