### ISSUE TITLE
Azure DevOps sign in uses inorrect URL format

### ISSUE THREAD

**Issue by mattwoolford** [GitLiveApp/GitLive#155]
I can't sign in to my organisation with a personal access token because GitLive attempts to do this at the endpoint

`https://visualstudio.com/<organisation>/...`

when it should be

`https://<organisation>.visualstudio.com/...`

and therefore the request fails.

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/6968525e-a74e-4841-91ca-1996582f3ce5">
<img width="1728" alt="Screenshot 2024-07-23 at 18 15 33" src="https://github.com/user-attachments/assets/84eea09f-92a6-43e7-86fa-bf93f1176f0a">

**Comment by nbransby** [comment]
Thanks for the detailed report @mattwoolford, we'll have someone look into it and get back to you

**Comment by mattwoolford** [comment]
Thanks @nbransby! On hand if you need anything else 🙌

**Comment by nbransby** [comment]
@mattwoolford The team have suggested a workaround until the issue is fixed which is to update your remote url in your local clone to the format with `dev.azure.com` as the host instead of `visualstudio.com`. 

Is that something you can try?

**Comment by mattwoolford** [comment]
@nbransby this has solved the sign in issue for now. For your benefit in terms of the workaround, the URL schema originally was

`https://<organisation>.visualstudio.com/DefaultCollection/<path>`

for the workaround to work this has to be changed to

`https://dev.azure.com/<organisation>/<path>`

Hope this is helpful to you!

**Comment by nbransby** [comment]
Thanks @mattwoolford , fixed in 18.0.0-eap3

**Comment by gerardoepitacio** [comment]
Sorry this might be obvious for some but not so much for others, the url should be done on the remote repository on you local git copy.

**Comment by nbransby** [comment]
@gerardoepitacio which version of GitLive are you using? I believe this was fixed in 18.0.0

**Comment by gerardoeg** [comment]
I'm using the Android Studio Plugin
![image](https://github.com/user-attachments/assets/dbb0ccd4-b8e1-46f6-84d5-8777bc014015)
