### ISSUE TITLE
Issues with IntelliJ Idea 2024.2

### ISSUE THREAD

**Issue by martinsuchenak** [GitLiveApp/GitLive#156]
The plugin reports issues after launching, see attached stacktract.
It also seem sto steal the focus from the dialogs. For example when opening the Add New Branch the focus is on the editor behind rather than the dialog. After disabling the plugin it all works as expected.

[stacktrace.txt](https://github.com/user-attachments/files/16573860/stacktrace.txt)

**Comment by nbransby** [comment]
Hi @martinsuchenak,

Thanks for the report, could you confirm which version of the plugin you are running? 

We are not able to reproduce the issue using the latest version (17.1.2)

**Comment by martinsuchenak** [comment]
Version 17.1.2

**Comment by nbransby** [comment]
Thanks @martinsuchenak, and could you confirm the exact version of IntelliJ Idea 2024.2? Hoping it might only be an issue with the EAP version

**Comment by martinsuchenak** [comment]
Yes it is 2024.2. I've never used the EAP version

**Comment by nbransby** [comment]
Hi @martinsuchenak we've released a EAP version of GitLive 18 that hopefully fixes this issue - you can see instructions to install the EAP version here: https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains#how-to-join-the-eap

**Comment by martinsuchenak** [comment]
I updated the GitLive 18 and the issue is gone
