### ISSUE TITLE
Focus lost in UI with 2024.2 Update

### ISSUE THREAD

**Issue by simfyz** [GitLiveApp/GitLive#159]
Please refer the issue reported here
[https://youtrack.jetbrains.com/issue/IJPL-160439/Focus-is-lost-with-context-windows-and-UIs](url)

**Comment by nbransby** [comment]
Hi @simfyz , could you confirm its still an issue with the  EAP version of GitLive 18 - you can see instructions to install the EAP version here: https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains#how-to-join-the-eap

**Comment by simfyz** [comment]
> Hi @simfyz , could you confirm its still an issue with the EAP version of GitLive 18 - you can see instructions to install the EAP version here: https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains#how-to-join-the-eap

I haven't tried it yet. I will try and get back.

**Comment by nadia-tarashkevich** [comment]
We have constant complains from users in https://youtrack.jetbrains.com/issue/IJPL-160439
The issue keeps getting upvoted.
https://youtrack.jetbrains.com/articles/SUPPORT-A-464/Popups-and-menus-are-no-longer-focused-in-IntelliJ-IDEs

**Comment by lutzleonhardt** [comment]
Also the switcher (CTRL + Tab) does not close in Jetbrains products (Rider, Webstorm for me). So I need to disable the plugin sadly, because I like it very much.

**Comment by lutzleonhardt** [comment]
BTW I faced this issue a long time ago the first time (before > 3 Months). Disabled it since then and tried it out again today with Rider 2024.2 (no EAP), problem still exists...

**Comment by lutzleonhardt** [comment]
Updated git live to eap version 18.0.0-eap3. I can confirm it is working now correctly. Thank you :)

**Comment by mathisgauthey** [comment]
Issue is occurring in `17.1.2` of the plugin.

I just installed `18.0.0-eap4` version and the issue is no longer occuring.

Here are YouTrack status of tickets related to this issue :
- https://youtrack.jetbrains.com/issue/IDEA-358441/When-opening-Recent-Files-focus-remains-on-the-edit-window (Duplicated)
- https://youtrack.jetbrains.com/issue/IJPL-160439/Focus-is-lost-with-context-windows-and-UIs (Original Bug)

**Comment by nbransby** [comment]
18.0.0 has now been released to stable, thanks for reporting.
