### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kstubhieeee** [GitLiveApp/GitLive#162]
- Issue Type: `Performance`
- Extension Name: `teamhub`
- Extension Version: `18.0.5`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.93.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/KAUSTU~1/AppData/Local/Temp/TeamHub.teamhub-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nbransby** [comment]
Thanks @kstubhieeee, could you attached the file?

**Comment by kstubhieeee** [comment]
Postman and GitLive extensions were causing this problem , so i disabled them and now it works perfectly fine

**Comment by nbransby** [comment]
Could you still share the file at file:///c%3A/Users/KAUSTU~1/AppData/Local/Temp/TeamHub.teamhub-unresponsive.cpuprofile.txt so we can fix the issue?

**Comment by kstubhieeee** [comment]
![image](https://github.com/user-attachments/assets/657e3516-98ee-4b2c-993d-9ef48027efaa)

**Comment by nbransby** [comment]
We are released version 18.0.6 of GitLive - could you confirm if it fixes this issue?
