### ISSUE TITLE
Cannot save the file after change

### ISSUE THREAD

**Issue by battirunner** [GitLiveApp/GitLive#164]
Type: <b>Bug</b>

When change something, saving file shows like hanged and can't throgh the all chnages and version related log

Extension version: 18.0.5
VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|36.00GB (18.53GB free)|
|Process Argv|--crash-reporter-id 4f6e79d5-53a8-49eb-8d4c-d5823346a6d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-c:31125598
autoexpandse:31146404
iacca2:31150323
cc771715:31146322

```

</details>

**Comment by nbransby** [comment]
How big is the file? And how many branches in your repository?

**Comment by dannyviiprus** [comment]
Same for me, saving / creating / renaming any file or folder take forever, have to disable all extensions to find out this one issue.

**Comment by nbransby** [comment]
Version 18.0.6 of GitLive has now been released - could you confirm if it fixes this issue?

**Comment by nbransby** [comment]
Could you confirm you still get these issues in the latest version (18.0.8)?
