### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by samfernandes03** [GitLiveApp/GitLive#166]
- Issue Type: `Performance`
- Extension Name: `teamhub`
- Extension Version: `18.0.6`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.94.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/SAMUEL~1/AppData/Local/Temp/TeamHub.teamhub-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nbransby** [comment]
@samfernandes03 could you attach the file mentioned in your report?

**Comment by AyomideA-S** [comment]
Here's the file:
[TeamHub.teamhub-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17368019/TeamHub.teamhub-unresponsive.cpuprofile.txt)

**Comment by nbransby** [comment]
@AyomideA-S thanks, we will review it.

In the meantime, could you check if this workaround also works for you? https://github.com/GitLiveApp/GitLive/issues/163#issuecomment-2408904606

**Comment by nbransby** [comment]
Could you confirm you still get these issues in the latest version (18.0.8)?

**Comment by AyomideA-S** [comment]
I just disabled and enabled the extension twice, and then I got the new version (18.0.8).
The performance issue isn't there again.
Thanks.
