### ISSUE TITLE
High CPU Load, File creation issues, Deprecated linting and more.

### ISSUE THREAD

**Issue by Kennitala** [GitLiveApp/GitLive#167]
The Extension is tainted and causes a plethora of issues for me. 
Most notably it caused deprecated linting for Python which caused me to not be able to write any Python code without issues. Creating a file takes forever, the files did not work properly - Hovering code produced a "Loading" message, I couldn't press enter for new line and more.

**Comment by nbransby** [comment]
Thanks for the report - could you open the developer tools and send us any cpu profile files listed there like in this screenshot
![image](https://github.com/user-attachments/assets/14a6638c-c1ca-4f02-a104-41b34c1c97c0)

**Comment by nbransby** [comment]
Could you confirm you still get these issues in the latest version (18.0.8)?
