### ISSUE TITLE
Bug extension crash

### ISSUE THREAD

**Issue by Loris-Beranger** [GitLiveApp/GitLive#168]
Type: <b>Bug</b>

Bug crash extension 

Extension version: 18.0.6
VS Code version: Cursor 0.37.1 (bee043c1bb0095dab94043787985ccfc7cc38e50, 2024-07-14T03:18:35.590Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|8.00GB (0.48GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by nbransby** [comment]
Could you confirm you still get this crash in the latest version (18.0.8)?
