### ISSUE TITLE
Reset configuration on WebStorm

### ISSUE THREAD

**Issue by elaleprieto** [GitLiveApp/GitLive#170]
Hi there!

Is there a way to reset the configuration on WebStorm? I'm seeing an error on several Bitbucket repositories, and I'm not sure, but I believe that removing the configuration and signing in again will fix it.

Thanks!

<img width="847" alt="Captura de pantalla 2024-10-30 a la(s) 05 08 20" src="https://github.com/user-attachments/assets/1d4d8001-d12f-4099-a29a-36ed4adf9609">

**Comment by nbransby** [comment]
You can try with a another install of WebStorm (EAP for example) but I suspect it might not be fixed by signing in again.

We'll look into it and get back to you.

**Comment by nbransby** [comment]
Hi, I believe this should be fixed in the latest version 18.0.4

**Comment by elaleprieto** [comment]
It's working on 18.0.4!!

Thanks team!!
