### ISSUE TITLE
Cannot select issue to work one

### ISSUE THREAD

**Issue by khatibtamal** [GitLiveApp/GitLive#35]
When I select an issue to work on. I get the following error.

![gitlive_error](https://user-images.githubusercontent.com/22264199/108643173-502d2c00-7477-11eb-9c6e-403e5e245c7a.png)

I dont use master branch, but main.

Thanks

**Comment by michaelprichardson** [comment]
Hi @khatibtamal, thanks for letting us know about this. Could you please let us know what version of the GitLive plugin you are currently using?

**Comment by khatibtamal** [comment]
hello @michaelprichardson I believe it is 10.0.5 

![git_live_version](https://user-images.githubusercontent.com/22264199/108940936-324ffa80-7622-11eb-9834-a64c301f3621.png)

**Comment by michaelprichardson** [comment]
Hi @khatibtamal, 

Apologies for the delay but I believe it should be fixed now. Your default branch should be set to main now.

Please let me know if you are still getting the error

**Comment by ash-hat** [comment]
Was this fixed applied to other issue trackers? I seem to be getting an identical error with the same cause, but I use GitHub instead of GitLab. I'm currently on 11.1.0 via JetBrains Rider 2020.3.4.

**Comment by michaelprichardson** [comment]
Hi @ash-hat 

Thanks for letting us know! Just want to find out a bit more info so I can help fix this. Is the message the same as above? Is it trying to checkout `master` and your repositories default branch is `main`? Did the default branch name for the repository change recently?

**Comment by ash-hat** [comment]
Yes, same error:
![screenshot of error](https://user-images.githubusercontent.com/5615358/112146126-329fcf00-8ba9-11eb-8aa7-8a5ee61b9cf5.png)
I also had the same branch names: `master` (old) and `main` (new).

The branch did change recently, about 36 hours ago. I noticed it after deleting my stale local branches, including `master`, a little past 24h after the name change.
