### ISSUE TITLE
Annoyance: stale branches from teammates show as conflicts

### ISSUE THREAD

**Issue by virtulis** [GitLiveApp/GitLive#44]
I like the gutter conflict feature but right now it's quite annoying when a teammate is working on another project and has an old branch checked out. 

It'd be nice to be able to ignore stale branches. Some options I see:

* Explicitly ignore teammate/branch until there are any changes.
* Option to ignore commits/changes that are N+ days old.
* Option to completely ignore offline teammates / teammates without this repo currently open in IDE (idk if it's something you know).

**Comment by Reedyuk** [comment]
Hi @virtulis, actually your third option is the easiest for us to implement so we can add that in one of the next releases

**Comment by J3m5** [comment]
Any news on this one ?
It's a bit annoying,
thanks !

**Comment by nbransby** [comment]
We will be expanding the options for what to show in the gutter (just conflicts / all changes, online users / all users) in an update this month.

In the meantime you can ask your teammates to remove stale working copies from GitLive if they are not using that copy anymore by right clicking it in the GitLive window and select *Remove from GitLive*

**Comment by nbransby** [comment]
@virtulis @J3m5 is this solved for you guys now? Now, if the branch no longer exists on the remote then the changes do not show

**Comment by virtulis** [comment]
Is that for 13.0.0? I most certainly see "changes" from a person who hasn't even opened the project (or GitLive?) for months, in a branch long deleted.

**Comment by nbransby** [comment]
@virtulis can you share a screenshot of the gutter popup for these changes?

**Comment by nbransby** [comment]
We now have a stale filter for the gutter which ignores changes older than 3 months which is on by default.

Please reopen this issue if this doesn't solve your use case 👍

**Comment by spence-novata** [comment]
@nbransby Any way we can get a config option to define "stale" 3 months is too long for us. We'd probably want to set this to 2-4 weeks

**Comment by nbransby** [comment]
Hi @spence-novata, makes total sense we'll try and it add it in the next release

**Comment by Ygnys** [comment]
Hi @spence-novata, stale filter (which was hard coded to 3 months) was replaced with the ability to filter by "last updated" from 24 hours up to 3 years in the newest EAP. Here you can find instructions on how to switch to EAP in [JetBrains](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains) and [VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode). Will be happy to hear how it works for you!
