### ISSUE TITLE
IntelliJ plugin: gitlab support is not functional

### ISSUE THREAD

**Issue by iamtakingiteasy** [GitLiveApp/GitLive#45]
In plugin description on https://plugins.jetbrains.com/plugin/11955-gitlive

    Open a repository from one of the supported cloud services (GitHub, GitLab, Bitbucket, Azure DevOps)

However only github account can be added in plugin settings, no other options available.

**Comment by nbransby** [comment]
hi @iamtakingiteasy, sorry about this,  it will be fixed in next version, in the meantime I believe if you open the repository in the IDE it should prompt you to sign in with GitLab in the GitLive window
