### ISSUE TITLE
12.0 - VSCode: Error with gitlab repo

### ISSUE THREAD

**Issue by J3m5** [GitLiveApp/GitLive#46]
I get this error at startup:

> ENOENT: no such file or directory, open 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/6198892/avatar.png&size=48'

**Comment by J3m5** [comment]
The bug is a blocking one, it prevent the extension from starting, thus rendering it unusable.

I couldn't find more info in the logs,
reverting back to 11.1.1 fix the problem.

**Comment by nbransby** [comment]
Hi @J3m5, sorry about this, could you see if 12.0.1 fixes your issue? Thanks

**Comment by J3m5** [comment]
12.0.1 fix the issue, thanks for the quick update @nbransby !
