### ISSUE TITLE
Showing message: The app could not get installed on Bitbucket Marcket place

### ISSUE THREAD

**Issue by thehardikmodha** [GitLiveApp/GitLive#47]
I am trying to install GitLive on Bitbucket but it shows me this messages.

At first I have opened the marketplace page then clicked on add button the clicked on grant and then it shows me this error:

The app could not be installed.

Please help me.

![Screenshot from 2021-04-06 20-36-35](https://user-images.githubusercontent.com/62694049/113733208-e19ae980-9717-11eb-98c6-1f6f70e917de.png)
![Screenshot from 2021-04-06 20-36-48](https://user-images.githubusercontent.com/62694049/113733214-e2cc1680-9717-11eb-8988-18488a65f541.png)
![Screenshot from 2021-04-06 20-37-01](https://user-images.githubusercontent.com/62694049/113733217-e364ad00-9717-11eb-89b0-3926dd70d806.png)

**Comment by michaelprichardson** [comment]
Hi @thehardikmodha,

Thanks for bringing this to our attention. I believe you should be able to install the GitLive app on BitBucket now.

Apologies for the delay

**Comment by nbransby** [comment]
@thehardikmodha please reopen if you issue is not solved, thanks
