### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pApY-Dalix** [GitLiveApp/GitLive#49]
command 'git.live.viewSettings' not found
command 'git.live.showAccountList' not found

I have restart VS, reinstall GitLive.

Help me please ^^'

![image](https://user-images.githubusercontent.com/12466017/114530899-aafb2c80-9c4b-11eb-9c86-97aba10bbb29.png)

**Comment by FredCoen** [comment]
Which version of GitLive have you installed? Can you open your command pallette and type "report" to report the issue to gitlive? I will have a look for you!

**Comment by pApY-Dalix** [comment]
>I am in version 12.0.1, I tried lower versions with the same result. Thanks for the "report" tip, but I think it's an internal problem.
>I think I need to delete the cache and the GitLive folder to allow a pure reinstallation, do you know where that would be?

**Comment by pApY-Dalix** [comment]
![image](https://user-images.githubusercontent.com/12466017/114855444-445e4600-9de6-11eb-9e3b-1d785e60151a.png)

>Ah :(

**Comment by FredCoen** [comment]
We could not reproduce your issue. What OS  and vs code version are you on?

**Comment by pApY-Dalix** [comment]
OS : Windows 10 (Windows_NT x64 10.0.19042)
VS Preview : 1.56.0-insider

**Comment by pApY-Dalix** [comment]
The extension does not create any files/folder in VS
I have checked in Visual Studio Code Insiders > ressources > app > extensions.

**Comment by pApY-Dalix** [comment]
I tested on the non-insider version of VS, same error :/

**Comment by pApY-Dalix** [comment]
I found the real VS extension file : User > .vscode-insiders > extensions
I deleted the GitLive file : teamhub.teamhub-12.0.3
Reinstall the plugin

Without success.

**Comment by nbransby** [comment]
@pApY-Dalix Im not sure what to suggest, we have not had any other reports on this issue. How are you installing the extension, from the marketplace?

**Comment by pApY-Dalix** [comment]
>I made several installation attempts, different version coming from the marketplace integrated to VS and the one coming from the VS website.
>I also found this in VS :
![image](https://user-images.githubusercontent.com/12466017/115360306-cd4af800-a1bf-11eb-877d-5b00eb2f9847.png)

>If it helps.

>It's a pity that such a bug prevents me from using this plugin, I was able to test it when it was in beta, I very liked it.

**Comment by nbransby** [comment]
Interesting! @pApY-Dalix This would imply you don't have the git extension installed, can you check the installed extensions? should be listed under built-in.

Do you know why you wouldnt have it installed?

**Comment by pApY-Dalix** [comment]
>If it is, it is well installed
![image](https://user-images.githubusercontent.com/12466017/115361289-bbb62000-a1c0-11eb-99e2-478f349bd322.png)
![image](https://user-images.githubusercontent.com/12466017/115361424-dc7e7580-a1c0-11eb-9456-5c61977fb20b.png)

**Comment by pApY-Dalix** [comment]
>I'm even connected in Git for the VS synchronization
![image](https://user-images.githubusercontent.com/12466017/115361773-2ff0c380-a1c1-11eb-98fa-9c148c2d1ad3.png)

**Comment by nbransby** [comment]
https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/git/src/api/extension.ts#L76

Need to find out why thats the case on your machine

**Comment by pApY-Dalix** [comment]
>I'm really sorry to have wasted your time, I didn't have Git on my machine despite VS and other software telling me otherwise.
>I did a basic installation of Git: https://git-scm.com/

>And everything works perfectly. 
>I'm sorry for all that, it's research for a basic error on my part.

**Comment by nbransby** [comment]
No problem, glad you fixed it!
