### ISSUE TITLE
No option to collaborate on VS Code for MacOS

### ISSUE THREAD

**Issue by jhiron-wf** [GitLiveApp/GitLive#52]
Q | A
--|--
OS | MacOS - Big Sur v11.2.3
VS Code Version | v1.55.2
Cloud Repo service | Github

I'm attempting to collaborate with one of my colleagues on a repository that has GitLive enabled. He is using a mixture of Windows and Ubuntu via WSL. We both have the extension installed and can see one another's status/what files we're working on, but only he has the pencil icon to start collaborating. When I hover over his name, all I see is the "call teammate" icon and when I hover over any of his files, all I have is the "Cherry pick all changes" icon and the "Open on github" icon.

I have tried the same process on Windows, no difference. I have also tried on an Ubuntu installation and this is the only time that we were able to collaborate on a file. Would anybody be able to help and clear up if I've gone wrong somewhere or if maybe there's an issue with cross-OS compatibility?

Another thing to note: The GitLive pane in VS Code looks different on Ubuntu (it matches the screenshots in the GitLive docs) to how it looks in MacOS, see screenshots below:

**MacOS:**
<img width="383" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/70009993/115235671-599ee180-a112-11eb-8196-7ce8d1c8bf89.png">

**Ubuntu:**
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/70009993/115235705-63284980-a112-11eb-91fc-3bf6719c47d8.png)

If any clarification is needed, please let me know!

**Comment by michaelprichardson** [comment]
Hi @jhiron-wf,

Thanks for all of the information! 

The collaboration feature has been moved inside of the call feature. Please make sure both plugins are the latest versions (12.0.3 for VS Code and 12.0.2 for JetBrains) and then you will both have the call button when hovering over each other's names. Once you are in the call you can share code from there. You can read more about it here, https://blog.git.live/gitlive-12.0-voice-and-video-calling-with-screen-code-share

Regarding the difference it in the GitLive pane in macOS and Ubuntu if you update to the latest version, they should both look the same (the macOS screenshot is the new UI).

**Comment by jhiron-wf** [comment]
@michaelprichardson 
Ahhhh, apologies for the confusion! That makes sense, amazing, thank you for your help 😄
