### ISSUE TITLE
Error while try to authenticate with IDE or install to new group

### ISSUE THREAD

**Issue by Trickfilm400** [GitLiveApp/GitLive#58]
Hey,

I am using JetBrains:
![image](https://user-images.githubusercontent.com/34717401/115970168-1349e800-a541-11eb-9a1a-2d62f723d75d.png)
While clicking on the top link, I will get redirected to the following URL on my own **GitLab Server**
`https://domain.tld/oauth/authorize?client_id=<client.id>&response_type=code&scope=openid&state=install&redirect_uri=https://app.git.live/gitlab/redirect`

and get this issue:
![image](https://user-images.githubusercontent.com/34717401/115970140-e1388600-a540-11eb-98f2-953f7ef7a1d1.png)

If I click the bottom link, this will be shown:
![image](https://user-images.githubusercontent.com/34717401/115970289-ba2e8400-a541-11eb-8a34-14327b813e45.png)

This happend today the first time, I installed the Application about a month ago

Tried to reinstall the Jetbrains plugin, deleted gitlive user out of jetbrains, a friend tried it, all the same error
Using: WebStorm 2021.1, Gitlab 13.11.1-ee and also 13.11.0-ee

Is it possible to write to the support like you see on the 3rd screenshot so they can reset the gitlab configuration or is this another problem?

Regards

**Comment by michaelprichardson** [comment]
Hi @Trickfilm400,

Thanks for letting us know! Could you verify that the redirect URL for the GitLive application on your instance is `https://app.git.live/gitlab/redirect`?

**Comment by Trickfilm400** [comment]
Hi,
The redirect url `https://git.live/gitlab/redirect`
Like on these screenshots:

![Screenshot_20210426-112627_Chrome.jpg](https://user-images.githubusercontent.com/34717401/116060706-64adc080-a682-11eb-84d4-f4af3af1f3a5.jpg)


Did the url change? 
I will try your redirect url later and let you know if it worked

**Comment by Trickfilm400** [comment]
I have changed the url, but still the same issue.
Maybe because it was first configured with the old url?

Should I contact the support the reset the server configuration?

**Comment by michaelprichardson** [comment]
Yes, that would be best. We can use your remote to figure out what the issue is

**Comment by michaelprichardson** [comment]
Hi @Trickfilm400,

Just wanted to find out if you managed to get in contact with support or got it working?

**Comment by Trickfilm400** [comment]
Fixed by resetting the GitLab config through support
👍🏻
