### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MarcelRaschke** [GitLiveApp/GitLive#63]
- Issue Type: `Bug`
- Extension Name: `teamhub`
- Extension Version: `12.1.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by MarcelRaschke** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 148149,
		"activateCallTime": 26,
		"activateResolvedTime": 64,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "TeamHub.teamhub",
				"_lower": "teamhub.teamhub"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by nbransby** [comment]
Thanks for the report @MarcelRaschke can you provide any more information like what were you doing in vscode when you got the issue?

**Comment by MarcelRaschke** [comment]
it was Extension Installation and maintaining vscode with github gitlab et …
