### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by harleyq44** [GitLiveApp/GitLive#64]
- Issue Type: `Performance`
- Extension Name: `teamhub`
- Extension Version: `12.1.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\couch\AppData\Local\Temp\TeamHub.teamhub-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nbransby** [comment]
hi @harleyq44 you forgot to attach the cpu profile

**Comment by harleyq44** [comment]
I'm so sorry, I don't know what I'm doing I'm new to the coding world and my vs coder started going crazy 🥺, can you tell me what you need and where I can find it 🥺

**Comment by nbransby** [comment]
No problem, just attach this file from your home-directory: c:\Users\couch\AppData\Local\Temp\TeamHub.teamhub-unresponsive.cpuprofile.txt

**Comment by nbransby** [comment]
Ok, maybe its been deleted already - if it happens again please attach the file, I will close this issue for now, thanks

**Comment by harleyq44** [comment]
im sorry i posted the file, but its new

**Comment by harleyq44** [comment]
[TeamHub.teamhub-unresponsive.cpuprofile.txt](https://github.com/GitLiveApp/GitLive/files/6517217/TeamHub.teamhub-unresponsive.cpuprofile.txt)
