### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by harleyq44** [GitLiveApp/GitLive#65]
- Issue Type: `Bug`
- Extension Name: `teamhub`
[TeamHub.teamhub-unresponsive.cpuprofile.txt](https://github.com/GitLiveApp/GitLive/files/6517111/TeamHub.teamhub-unresponsive.cpuprofile.txt)

- Extension Version: `12.1.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
teamhub.teamhub

**Comment by harleyq44** [comment]
i think i put one file here

**Comment by nbransby** [comment]
great thanks!

**Comment by harleyq44** [comment]
👌
