### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nrafal** [GitLiveApp/GitLive#69]
- Issue Type: `Performance`
- Extension Name: `teamhub`
- Extension Version: `13.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:[TeamHub.teamhub-unresponsive.cpuprofile.txt](https://github.com/GitLiveApp/GitLive/files/6775030/TeamHub.teamhub-unresponsive.cpuprofile.txt)

**Comment by nrafal** [comment]
I can't get it to work. I've installed app on JIRA, BitBucket. I have successfully authorized myself, but extension just hangs and do nothing :(

**Comment by michaelprichardson** [comment]
Hi @nrafal,

Thanks for reporting this to us! We have managed to reproduce this issue and are working on a fix.

**Comment by michaelprichardson** [comment]
We have fixed this issue, please update to the latest version of GitLive
