### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by harleyq44** [GitLiveApp/GitLive#70]
- Issue Type: `Bug`
- Extension Name: `teamhub`
- Extension Version: `13.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by harleyq44** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21267,
		"activateCallTime": 43,
		"activateResolvedTime": 92,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "TeamHub.teamhub",
				"_lower": "teamhub.teamhub"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by nbransby** [comment]
We have improved the code load time in the latest version - please let us know if you still get this issue
