### ISSUE TITLE
"GitLive Show other's changes" is greyed out

### ISSUE THREAD

**Issue by maartenbergmans** [GitLiveApp/GitLive#74]
![image](https://user-images.githubusercontent.com/70018656/126900584-2034a2e0-ecdd-4b7d-addf-36185d4804cc.png)
For some reason in the phpstorm editor Git Live shows other changes is disabled.
The plugin is working. I can see my teammates and the files they have in use.

**Comment by maartenbergmans** [comment]
Found the issue. I used tortoise git instead of phpstorm git. 
It works when I pulled the last version of the application via tortoise git. When different users are on the same version it works fine.

**Comment by nbransby** [comment]
Hi @maartenbergmans its disabled when are not changes to show (your teammates haven't made changes to the file). Was that the case too?

**Comment by maartenbergmans** [comment]
> Hi @maartenbergmans its disabled when are not changes to show (your teammates haven't made changes to the file). Was that the case too?

Thank you for the feedback, this was not the case. But if one of us worked on a different starting version (did not pull via tortoise git before the person making the change). It stayed grayed out. We linked in phpstorm now our git-account directly which solves the problem.

We like your software very much now!
