### ISSUE TITLE
[Feature] Jetbrains Space support?

### ISSUE THREAD

**Issue by jayjah** [GitLiveApp/GitLive#75]
Do you plan to support [Jetbrains Space Repository](https://www.jetbrains.com/help/space/repositories.html) in near future?

**Comment by nbransby** [comment]
Hi @jayjah we'll add it to the roadmap, the more likes this issue gets the more we will prioritise it!

**Comment by Subtixx** [comment]
Shame more than a year has passed and no updates and still no support.

**Comment by Ygnys** [comment]
Hi @Subtixx, sorry we don't have any updates for you, we haven't forgotten about Space support but as this issue hasn't received many likes we haven't made it a priority. This can always change if we see more demand for it so don't lose hope!
