### ISSUE TITLE
intellij not showing conflicts

### ISSUE THREAD

**Issue by clement-boret** [GitLiveApp/GitLive#76]
Hello.
I am intersted in the "conflict detection feature" your plugin provides.

I installed it on Intellij 2021.1.2
I see at the bottom of the screen the gitLive tab (as on this picture: https://docs.git.live/uploads/jetbrains-installed-3.jpeg)

I have 3 branches in my repo: 
-main
-first
-second

they all "points" to the same commit.
I create a new commit on "first" branch that modifies "myFile.java"
I modify on "second" branch the file "myFile.java"

At this step I was expecting to see something from the gitLive plugin but I do not see anything telling me that there is a conflict...

I am 100% sure that there is indeed a conflict because when I want to merge "first" branch with "second" branch I get a conflict that needs to be resolved...

**Comment by nbransby** [comment]
Hi @clement-boret, currently the plugin only show changes from branches that are actively being worked on - so checked out by you or one of your teammates, you can see this by opening a second clone of your repo thats on the main branch whist your original clone is still on the second branch.

We will be adding the option to see changes from all branches in an update coming soon.

**Comment by clement-boret** [comment]
@nbransby  
Thank you for you answer. I am still trying to get something out of your plugin for the git conflict detection....
I however do not understand how to proceed:
1) Does the git conflict detection works if I only have a LOCAL repo ? (ie I do not have any remote setup)
2) here is an example step by step where I would expect to see some conflict detection:

I create a git repo with only one file in it and only one branch `master`.
I create a branch called `conflict`
I checkout `master`
I make a change in the file and commit in `master`
I checkout `conflict` branch and make a change that would conflict with the commit and just made in `master`
I am expecting to see something in the editor thanks to your plugin but it s not the case....

<img width="646" alt="Screenshot 2021-08-12 at 13 44 25" src="https://user-images.githubusercontent.com/73640971/129191516-c82bf37c-2af5-4b37-932e-4db3d2f8e162.png">

What should I do to get conflict detection shown by your plugin ?


3)when you say `branches that are actively being worked on ` what do you mean exactly? (in my example I consider that I am actively working on master branch AND on conflict branch.... am I not ?)

**Comment by nbransby** [comment]
1. No, as its designed for teams currently it requires a remote - check the GitLive window that should be showing your repo collaborators before the merge conflicts will show
3.  I mean you need to have both branches checked out as your HEAD, so you would need two clones of the repo on your machine in your case

**Comment by clement-boret** [comment]
@nbransby  Thank you for the explanation. 
I finally managed to get something shown by the plugin.

<img width="118" alt="Screenshot 2021-08-13 at 08 52 34" src="https://user-images.githubusercontent.com/73640971/129316769-65eeb589-95ea-46c1-b40e-1eed907acf1e.png">

Now that I understand it a bit more I have further question/suggestion:

1) When I open the file, even if I have not edited it yet , I see the icon of the person who changed the file... can this feature be removed : I must say that I am only interested in showing conflicts. If there is no conflict I do not want to display any icon
<img width="148" alt="Screenshot 2021-08-13 at 08 58 07" src="https://user-images.githubusercontent.com/73640971/129317285-96c52919-cc29-42b9-bcb0-15fef435fa16.png">

2) you said `We will be adding the option to see changes from all branches in an update coming soon.`
Will this feature also include something to show conflicts without 2 HEADS (meaning without 2 clones of the repo).

thank you.

**Comment by nbransby** [comment]
@clement-boret we'll try and add both these features to the next major release (thats monthly-ish)
