### ISSUE TITLE
Could not determine Git hosting service from remote URL

### ISSUE THREAD

**Issue by diegoasanch** [GitLiveApp/GitLive#78]
Hi!

I get the following message `Could not determine your Git hosting service from your remote URL` when trying to use the extension while on a repo in which the remote URL has the form `git@github.com-userName:repository_name.git`. I use it this way since I use different SSH keys for my GitHub accounts.

This is how it looks on VScode
![image](https://user-images.githubusercontent.com/87026771/129032377-ac220545-6551-4a4d-9450-927a3b298374.png)

**Comment by Reedyuk** [comment]
we are looking into it

**Comment by Reedyuk** [comment]
HI @diegoasanch - is this a custom git config? I havent seen this before. If for now, we currently dont support custom git configs, the work around is to change the remote to the real remote.

**Comment by diegoasanch** [comment]
Hi! @Reedyuk, the only modification made to the git config is on the remote url as mentioned, I'm using this approach [Using multiple GitHub accounts with SSH keys](https://gist.github.com/jexchan/2351996)

**Comment by Reedyuk** [comment]
Yes its a fairly common pattern when dealing with multiple ssh keys. Its in the roadmap to support git config, i will speak with my colleagues about making this a higher priority. I will let you know when its released in this ticket.
Unfortunately for now, to use gitlive, you will need to keep that remote url the actual url and not an alias.

**Comment by diegoasanch** [comment]
Ok, I guess I'll do it that way until it's implemented. Thanks!

**Comment by Reedyuk** [comment]
Hi @diegoasanch - Great news, we now support git config, can you make sure you have the latest plugin and try it out. I'm going to close this issue now but feel free to reopen it, if it doesnt work for you.
