### ISSUE TITLE
GitLab Integration: The redirect URI included is not valid

### ISSUE THREAD

**Issue by dpankros** [GitLiveApp/GitLive#84]
From https://git.live/ scroll down to GitLab in the “Integrate Your Stack” section. Click on “Integrate Now” for GitLab.  
After authenticating to GitLab, the following is received:
> An error has occurred
> The redirect URI included is not valid.

**Comment by Reedyuk** [comment]
@dpankros - we will have a look into it for you.

**Comment by michaelprichardson** [comment]
Hi @dpankros,

Thanks for reporting this. We have fixed the Gitlab integration URL and should be working now

**Comment by dpankros** [comment]
That link now works.  Thanks.

  When I completed the onboarding flow (following the additional JIRA integration path) it prompted me to install in my IDE and gave another dead link: https://git.live/instal
![Screen Shot 2021-09-21 at 9 33 00 AM](https://user-images.githubusercontent.com/7989367/134180168-ba48d110-df0b-422c-9c90-411cb1b8776b.png)
Clicking install leads to
![Screen Shot 2021-09-21 at 9 33 35 AM](https://user-images.githubusercontent.com/7989367/134180298-10191069-3fb2-46b5-b13a-a46592c5495a.png)

**Comment by michaelprichardson** [comment]
Thanks again for reporting this to us @dpankros

**Comment by michaelprichardson** [comment]
@dpankros we've fixed the broken URLs. I'm going to close the issue.
