### ISSUE TITLE
VSCode - Code action never finishes

### ISSUE THREAD

**Issue by ValentinVignal** [GitLiveApp/GitLive#89]
I'm using the VSCode extension on a flutter project.

In my `settings.json` I have:

```json
{
  "editor.codeActionsOnSave": {
    "source.organizeImports": true,
  },
}
```

When the extension is enabled, every time I try to save a file, I get the info message 

```
Saving 'drawing_test.dart': Getting code actions from ''Dart''
```

which never finishes and blocks VSCode other commands/actions.

![image](https://user-images.githubusercontent.com/32538273/139197181-989fd31d-9c5f-4867-9b90-c8bc407a919c.png)

---

When I disable the extension, the info message appears and quickly go away without blocking anything.

**Comment by ValentinVignal** [comment]
Hello @Ygnys, here is a list of the extension that could maybe impact/conflict. (It didn't put all of them as I have a lot of them):
- [Awesome Flutter Snippets](https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- [Dart](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code)
- [Flutter](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter)
- [Git Blame](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame)
- [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)
- [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory)
- [GitLens - Git supercharged](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
- [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave)

**Comment by Ygnys** [comment]
Hi @ValentinVignal, thanks for the reply.
Would it be possible for you to report a performance issue in VS Code as well? 

To report a performance issue please use the 'Report Issue' command available in the 'Help' menu. In the Issue Reporter window that shows up, set the issue type to 'Performance Issue', file on 'An Extension' and then choose GitLive. Thanks!

![image (4)](https://user-images.githubusercontent.com/51296866/139850491-270cbb69-5dc6-4bb2-bb61-065fa720ea8d.png)

**Comment by ValentinVignal** [comment]
@Ygnys Since I created another issue https://github.com/GitLiveApp/GitLive/issues/92 , should I close this one ?

**Comment by Ygnys** [comment]
Yes, thanks!

**Comment by Ygnys** [comment]
I am going to close this issue, please refer to #92 instead
