### ISSUE TITLE
High memory usage in VS Code

### ISSUE THREAD

**Issue by Ygnys** [GitLiveApp/GitLive#93]

**Comment by Ygnys** [comment]
The fix has been included in the latest version. To try it out, please make sure to install the latest version of the extension available as a Pre-Release for VS Code. (Here you can find more on [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)).

**Comment by nbransby** [comment]
Closing as this has now been released to stable
