### ISSUE TITLE
Support for JetBrains EAP

### ISSUE THREAD

**Issue by byymster** [GitLiveApp/GitLive#94]
We have self hosted Gitlab and security restriction for our network.
Can you please provide IP's (or ranges) of Git.Live so we can allow this connections to be able make integration?

**Comment by Ygnys** [comment]
Hey, unfortunately, our setup doesn't include static IPs we could share. We are in the process of adding an offline mode that supports a number of our features without sending any traffic outside your network, maybe this will be useful in your case. The good news is it will be available in the next few months. I have opened a separate issue for that https://github.com/GitLiveApp/GitLive/issues/96

**Comment by Ygnys** [comment]
@byymster  Great news, we now support offline mode which supports a number of our features without sending any traffic outside your network! To try it out, please make sure to install the latest version of the plugin available in EAP channel for JetBrains and Pre-Release for VS Code. (Here you can find more on [GitLive's EAP for JetBrains](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains) and [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)). Will be happy to hear how it works for you!

**Comment by byymster** [comment]
Hi @Ygnys 
thanks for the update,
I already tested and looks good, unfortunately eap version of plugin didn't work with eap PhpStorm
Do you plan to add another features to offline mode?

**Comment by Ygnys** [comment]
@byymster Thanks for reporting, we will look into that issue. 
Appreciate your feedback, do you have any specific features in mind that you'd like to see added to the offline mode?

**Comment by Ygnys** [comment]
Hi @byymster, the newest version of the plugin works with all JetBrains EAPs.
