### ISSUE TITLE
Bugged Session

### ISSUE THREAD

**Issue by michiexe** [GitLiveApp/GitLive#95]
So me and my friend are often working together in IntelliJ via GitLive but we have encountered an issue for almost a week now. So we didn't end the code-sharing session before shutting down IntelliJ and our computers. A day later we wanted to continue working together but couldn't open a new session. Both of our icons in the GitLive Toolbar are now constantly marked as the color red and we have no option to open a new session nor end the old session. We both tried to reinstall the plugin but it didn't fix the issue nor did it work to delete access on our GitHub accounts and the repository. It would be nice to have an option to force-end sessions.

![image](https://user-images.githubusercontent.com/42840496/143725918-d37be2fc-5973-4cc8-9a4a-2a9b07ad9910.png)

**Comment by Reedyuk** [comment]
Thanks for reporting, i have found your record of the stuck call and deleted it, you should be able to call/use gitlive again.
We will look into the issue separately, thanks for raising it.
