### ISSUE TITLE
GitLive offline mode

### ISSUE THREAD

**Issue by Ygnys** [GitLiveApp/GitLive#96]
An offline mode removes installation requirement and supports a number of our features without sending any traffic outside your network.

**Comment by Ygnys** [comment]
Great news, we now support offline mode! To try it out, please make sure to install the latest version of the plugin available in EAP channel for JetBrains and Pre-Release for VS Code. (Here you can find more on [GitLive's EAP for JetBrains](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-JetBrains) and [GitLive's EAP for VS Code](https://blog.git.live/Introducing-GitLive-Early-Access-Program-for-VSCode)). Will be happy to hear how it works for you!

**Comment by nbransby** [comment]
Closing as this has now been released to stable
