### ISSUE TITLE
vscode Sign in with GitLab

### ISSUE THREAD

**Issue by Dylan0203** [GitLiveApp/GitLive#97]
Was having trouble working on some of the projects with the GitLab group
<img width="317" alt="Screen Shot 2021-12-04 at 18 07 01" src="https://user-images.githubusercontent.com/16032822/144705601-79d1f96d-a546-4805-ac60-6b04908c1130.png">
then I removed the extension & revoke app access
now I can never sign in with GitLab

after reinstalling & signing in with GitLab that seems successfully redirected to the project list page which told me I can close the tab and return to IDE
but it still shows not signed in
<img width="330" alt="Screen Shot 2021-12-04 at 18 09 52" src="https://user-images.githubusercontent.com/16032822/144705672-6d42be8d-d50e-46ff-8238-de880923daf9.png">

Also I don't have the remove account for the GitLab option
<img width="500" alt="Screen Shot 2021-12-04 at 18 16 48" src="https://user-images.githubusercontent.com/16032822/144705834-026b063c-4655-496b-b11e-1a68f0d23f42.png">

Is there a way to fully clean the extension caches somehow?
or what can I do to make it works again?

**Comment by SP-84** [comment]
Just to say that I am stuck with the same issue, I tried to reinstall the extension and to reload vscode, but it refuses to sign-in to my GitHub account. Maybe there is a bug with the current vscode version ?
![Screenshot_20211206_134400](https://user-images.githubusercontent.com/66826625/144848435-6614683d-bd0a-462a-a500-52efd6a88a5f.png)

**Comment by SP-84** [comment]
Also see : https://github.com/microsoft/vscode/issues/92972#issuecomment-625751232
Installing `gnome-keyring` (and/or additionnal packages depending on your Desktop Environment) seems to fix the issue.

**Comment by Ygnys** [comment]
@Dylan0203 @SP-84 Thanks for reporting! We have now included a fix for this, so you should be able to sign in again.

**Comment by Dylan0203** [comment]
@Ygnys 

After I revoke the GitLab application access, I can sign in again.
thx!!
