### ISSUE TITLE
Gitlive has stopped due to an uncaught exception

### ISSUE THREAD

**Issue by seonglae** [GitLiveApp/GitLive#99]
![image](https://user-images.githubusercontent.com/27716524/146703476-0d576d93-7ec5-4719-afa1-f108b4322ae5.png)

![image](https://user-images.githubusercontent.com/27716524/146703479-433b31d6-3c64-480b-ac1c-66f4c9d4559e.png)

- vscode 1.63.2
- gitlive 14.0.8
- azure devops

Can't I just restart gitlive only without need to restart whole vscode?

**Comment by Steakeye** [comment]
Hi @seonglae, would it be possible for you to provide more details on how to reproduce this error?
Ideally, we'd be grateful if you could send us a bug report from VS Code.

To do it:

- navigate to Help > Report Issue.
- In the Issue Reporter window that shows up, set the issue type to 'Bug Report', select source: 'An Extension', then choose GitLive.

![image](https://user-images.githubusercontent.com/8146520/148250555-5cbe977a-4838-44cc-a380-6a3da67d310d.png)

If it's possible to record a video, then please email that to support@git.live.

Thanks!

**Comment by seonglae** [comment]
I forgot to reproduce, sorry
